name: Update submodules
on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
jobs:
  update_submodules:
    name: Update submodules
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - name: Update submodules
      run: git submodule update --remote --recursive 
    - name: Add and commit files
      run: |
        git config user.email "github-actions@github.com"
        git config user.name "GitHub Action"
        git add .
        git commit -m "Update submodule"
        git push
