name: Rating / Contest Update

on :
  push:
    branches: 
      - main
    paths:
      - .github/workflows/**
  schedule: 
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Update submodules
        run: |
          git submodule update --remote --recursive
      - name: Add and commit files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "updated submodules"
          git push
