name: Update submodules
on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
jobs:
  build:
    name: Update submodules
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with: 
        # repository: org/parent_repository
        # token: ${{ secrets.PRIVATE_TOKEN_GITHUB }}
        submodules: true
    - name: Update submodules
      run: |
        git pull
        git submodule update --init --recursive
        git submodule update --remote --recursive 
    - name: Add and commit files
      run: |
        git config user.email "github-actions@github.com"
        git config user.name "GitHub Action"
        git add .
        git commit -m "Update submodules" || echo "No changes to commit"
        git push
